-- liquibase formatted sql

SELECT 'CREATE DATABASE postmail'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'postmail');

-- changeset Vlad:1653230153320-1
CREATE TABLE POSTAL_DELIVERY
(
    ID            UUID,
    CREATE_TS     TIMESTAMP WITHOUT TIME ZONE,
    UPDATE_TS     TIMESTAMP WITHOUT TIME ZONE,
    IDENTIFIER    VARCHAR(255),
    POST_TYPE     VARCHAR(255),
    INDEX         VARCHAR(255),
    ADDRESS       VARCHAR(255),
    RECEIVER_NAME VARCHAR(255),
    primary key (ID)
);

-- changeset Vlad:1653230153320-2
CREATE TABLE POSTAL_JOURNAL
(
    ID                     UUID,
    CREATE_TS              TIMESTAMP WITHOUT TIME ZONE,
    UPDATE_TS              TIMESTAMP WITHOUT TIME ZONE,
    POSTAL_DELIVERY_ID     UUID,
    POSTAL_OFFICE_ID       UUID,
    POSTAL_DELIVERY_STATUS VARCHAR(255),
    primary key (ID)
);

-- changeset Vlad:1653230153320-3
CREATE TABLE POSTAL_OFFICE
(
    ID        UUID,
    CREATE_TS TIMESTAMP WITHOUT TIME ZONE,
    UPDATE_TS TIMESTAMP WITHOUT TIME ZONE,
    INDEX     VARCHAR(255),
    NAME      VARCHAR(255),
    ADDRESS   VARCHAR(1000),
    primary key (ID)
);

-- changeset Vlad:1653230153320-4
ALTER TABLE POSTAL_JOURNAL
    ADD CONSTRAINT FK_POSTAL_JOURNAL_ON_POSTAL_DELIVERY FOREIGN KEY (POSTAL_DELIVERY_ID) REFERENCES POSTAL_DELIVERY (ID);

-- changeset Vlad:1653230153320-5
ALTER TABLE POSTAL_JOURNAL
    ADD CONSTRAINT FK_POSTAL_JOURNAL_ON_POSTAL_OFFICE FOREIGN KEY (POSTAL_OFFICE_ID) REFERENCES POSTAL_OFFICE (ID);

